DROP TABLE CITY;
DROP TABLE USER;

CREATE TABLE CITY (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `NAME` varchar(255),
    `PHOTO` varchar(1000)
);

CREATE TABLE `USER` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(64) NOT NULL,
  `ROLE` varchar(45) NOT NULL,
  `ENABLED` tinyint(4) DEFAULT NULL,
  `HAS_EDIT_ACCESS` BOOLEAN DEFAULT FALSE,
   PRIMARY KEY (`USER_ID`)
);